### ISSUE TITLE
Letters disappear in nano

### ISSUE THREAD

**Issue by humky** [ashish-yadav11/st#3]
I have some visual glitches in nano (5.9) when navigating the cursor along the lines (horizontally) by holding left or right arrow. Some letters disappear. I believe the issue is in the scroll patch because I have my own heavily patched version of st and it doesn't have this bug. The bug appears in your build, or in my build after your scroll/reflow integration. vim doesn't have this bug. I use bspwm if it has any importance.

**Comment by ashish-yadav11** [comment]
Try changing minlatency and maxlatency to default values in config.h.

**Comment by ashish-yadav11** [comment]
I am not able to reproduce the issue.

**Comment by ashish-yadav11** [comment]
Morever scroll/reflow only comes into play when resizing the st window.

**Comment by humky** [comment]
latency didn't help, set to 30, 80, cursor is very leggy, bug persists.

**Comment by ashish-yadav11** [comment]
Can you send a video or something?

**Comment by ashish-yadav11** [comment]
Default latency is 8, 33 by the way.

**Comment by humky** [comment]
Tried with freshly compiled nano 5.8
https://fastupload.co/1111217

Tried without .bashrc, same.

**Comment by ashish-yadav11** [comment]
One thing is for sure that it is not being caused by scrolling/reflow part. Scrolling/reflow doesn't happen on alt-screen. Also I am not being able to reproduce the issue (but I have nano 5.9). I wouldn't be able to help you with the issue for a week or so. I have my exams from tomorrow.

**Comment by ashish-yadav11** [comment]
If you can, you can try to find changes I have made in CSI code handlings related to cursor movement (see commit 4e9d5c5eb22754e9df6553d39dec4fe27b8727ca). I think some bug there might be causing the issue.

**Comment by humky** [comment]
Sorry my knowledge of C is very superficial, I can't help with source that much. It shouldn't matter though, If you can't reproduce it, it has to be something else, we have the same source code, computers supposed to be deterministic? Then it's some other code which is different on our machines.

**Comment by ashish-yadav11** [comment]
The bug is happening in the build on this repository only, right?

**Comment by humky** [comment]
> The bug is happening in the build on this repository only, right?

yes, my own build, and default st is fine.

**Comment by ashish-yadav11** [comment]
Are you sure you are on the latest commit?

**Comment by humky** [comment]
git log -i
commit ade8fcdfeae20d865490f9a0af30659fd438f50f (HEAD -> main, origin/main, origin/HEAD)

I just git clone it, I didn't touch the head or anything

**Comment by ashish-yadav11** [comment]
I will relook into this after a week.

**Comment by humky** [comment]
Ok. I will poke some more, maybe I'll find something.

--

Works fine in tmux

**Comment by humky** [comment]
92c5965daf4e951a6fc1ff86d35a32650d0e5425 introduces it

**Comment by humky** [comment]
Using old
```
void
tputtab(int n)
{
    uint x = term.c.x;

    if (n > 0) {
        while (x < term.col && n--)
            for (++x; x < term.col && !term.tabs[x]; ++x)
                /* nothing */ ;
    } else if (n < 0) {
        while (x > 0 && n++)
            for (--x; x > 0 && !term.tabs[x]; --x)
                /* nothing */ ;
    }
    term.c.x = LIMIT(x, 0, term.col-1);
}
```
```
void
tcontrolcode(uchar ascii)
{
    switch (ascii) {
    case '\t':   /* HT */
        tputtab(1);
```
fixes it.

That's my limit in understanding. good luck on the exams

**Comment by ashish-yadav11** [comment]
Are you completely sure that replacing twritetab() with tputtab(1) fixes the issue? I am unable to understand how the tabbing thing could lead to washing out of characters on moving the cursor.

**Comment by humky** [comment]
Yes, you still have this function defined, just replacing twritetab() with tputtab(1) solves missing characters. If you have any ideas how to debug I can try that.

**Comment by ashish-yadav11** [comment]
Undo all changes, in twritetab function, replace GLYPH_TAB and GLYPH_TDUMMY with GLYPH_SET. See if the issue occurs.
Also did you observe the behaviour in any program other than nano?

**Comment by humky** [comment]
What do you mean undo all changes? It was written from scratch and at the same commit it became buggy. Changing GLYPH_TAB and GLYPH_TDUMMY with GLYPH_SET didn't help. No, only in nano.

Tried most recent, and at the point of first introduction, with GLYPH_SET, still bugy.

**Comment by ashish-yadav11** [comment]
I meant the changes you might have made.

**Comment by ashish-yadav11** [comment]
Work on the latest state/commit. Comment out "if selected" and "selclear" lines from the twritetab function. See if the issue persists.

**Comment by humky** [comment]
Same.

**Comment by ashish-yadav11** [comment]
Try this

```
void
twritetab(void)
{
	int x = term.c.x, y = term.c.y;

	/* selected() takes relative coordinates */
//	if (selected(x + term.scr, y + term.scr))
//		selclear();

//	term.line[y][x].u = ' ';
//	term.line[y][x].state = GLYPH_TAB;

	while (++x < term.col && !term.tabs[x]) {
//		term.line[y][x].u = ' ';
//		term.line[y][x].state = GLYPH_TDUMMY;
	}

	term.c.x = MIN(x, term.col-1);
}
```

**Comment by humky** [comment]
It still bugs out, but I think it somehow different to the previous time. Letters are shifting or something, not just disappearing, and it happens less frequently.

I tried in a new document, even without tabs still the same.

**Comment by ashish-yadav11** [comment]
Wait this is impossible. The change must be equivalent to replacing twritetab with tputtab(1). Anyhow replace
```
	term.c.x = MIN(x, term.col-1);
```
with
```
	term.c.x = LIMIT(x, 0, term.col-1);
```
in the function.

**Comment by ashish-yadav11** [comment]
If that also doesn't work, try
```

void
twritetab(void)
{
	uint x = term.c.x;

	if (x < term.col)
		for (++x; x < term.col && !term.tabs[x]; ++x)
	term.c.x = LIMIT(x, 0, term.col-1);
}
```

**Comment by humky** [comment]
```
void
twritetab(void)
{
	int x = term.c.x, y = term.c.y;

	/* selected() takes relative coordinates */
//	if (selected(x + term.scr, y + term.scr))
//		selclear();

//	term.line[y][x].u = ' ';
//	term.line[y][x].state = GLYPH_TAB;

	while (++x < term.col && !term.tabs[x]) {
//		term.line[y][x].u = ' ';
//		term.line[y][x].state = GLYPH_TDUMMY;
	}
        term.c.x = LIMIT(x, 0, term.col-1);
}
```
Works, I had issues with copying it from github, it produces additional //

**Comment by ashish-yadav11** [comment]
Commented lines are not changing in the first part, weird.

**Comment by ashish-yadav11** [comment]
wtf. In twritetab just write tputtab(1), remove everything else. what happens then?

**Comment by ashish-yadav11** [comment]
Now uncomment first two commented lines. What happens then?

**Comment by humky** [comment]
```
void
twritetab(void)
{
    int x = term.c.x, y = term.c.y;

    /* selected() takes relative coordinates */
    if (selected(x + term.scr, y + term.scr))
         selclear();

  //  term.line[y][x].u = ' ';
  //  term.line[y][x].state = GLYPH_TAB;

      while (++x < term.col && !term.tabs[x]) {
      //      term.line[y][x].u = ' ';
      //      term.line[y][x].state = GLYPH_TDUMMY;
          }
              term.c.x = LIMIT(x, 0, term.col-1);
}
```
This one is working

**Comment by ashish-yadav11** [comment]
Now uncomment GLYPH_* lines.
Also revert last line to what it used to be (term.c.x = MIN(..)).

**Comment by humky** [comment]
Without term.line[y][x].u = ' ';?

**Comment by ashish-yadav11** [comment]
yes

**Comment by humky** [comment]
Still working.

What it does?

**Comment by ashish-yadav11** [comment]
Now uncomment first of the left ones (not in the loop).

**Comment by humky** [comment]
Bugs out

**Comment by ashish-yadav11** [comment]
> Still working.
> 
> What it does?

These are "hacks" for implementing copying of tab characters in the terminal.

**Comment by ashish-yadav11** [comment]
> Bugs out

What do you mean? Uncommenting all lines also doesn't cause any issue?

**Comment by humky** [comment]
uncomenting 
`term.line[y][x].u = ' ';`
outside of while starts bugging again.
second one remains commented

**Comment by ashish-yadav11** [comment]
Okay, are you using tab keys for movement by any chance?

**Comment by humky** [comment]
I use arrows which are 
`KC_LEFT,  KC_DOWN,   KC_UP,      KC_RGHT`
in qmk firmware.
I also have this `stty werase '^H'` in .bashrc, to have Ctrl-Backspace delete whole word.
My .inputrc doesn't have anything unusual.

**Comment by ashish-yadav11** [comment]
Can you try lxterminal and see if you face the same issue in nano? It also has the capability of copying tab characters.

**Comment by humky** [comment]
lxterminal 0.4.0 works fine.

**Comment by ashish-yadav11** [comment]
It could be a bug in nano. Pressing movement keys should not lead to sending tab characters in my limited knowledge.

**Comment by ashish-yadav11** [comment]
> lxterminal 0.4.0 works fine.

hmm.

**Comment by humky** [comment]
Why can't you reproduce?

**Comment by ashish-yadav11** [comment]
I have no idea.

**Comment by ashish-yadav11** [comment]
What version of nano are you using? What distro?

**Comment by humky** [comment]
I will try much older nano

**Comment by humky** [comment]
I tried 5.8 and 5.9 (gentoo)

**Comment by ashish-yadav11** [comment]
Are there any configuration options for nano? Have you changed any?

**Comment by ashish-yadav11** [comment]
Anyway I will try adding a fix.

**Comment by humky** [comment]
I haven't changed anything.
nano 3.1 (2018-09-18) (official git, not gentoo's) still the same.

**Comment by ashish-yadav11** [comment]
Hmm I think its my ignorance. Let me do some read up about function of tabs.

**Comment by humky** [comment]
Can your fix break something else? What should I look up for?

**Comment by ashish-yadav11** [comment]
No it is safe to comment the two line. Meanwhile I will get a better fix.

**Comment by ashish-yadav11** [comment]
One last thing, can you try rxvt-unicode once, if it has the issue with nano?

**Comment by humky** [comment]
I think my urxvt is patched slightly, (truecolor patch), but the one I have installed works fine.

**Comment by ashish-yadav11** [comment]
Okay.

**Comment by ashish-yadav11** [comment]
I have added a fix to the repo. Can you confirm that the issue doesn't occur anymore? Most likely I will remove this copying tab stuff in the future. But this fix will do for now.

**Comment by humky** [comment]
https://fastupload.co/1111526

**Comment by ashish-yadav11** [comment]
Try this. After the first while loop in twritetab, add `fprintf(stderr, "writing tab\n");`. After compilation launch by ./st, see if "writing tab" gets printed when letters start disappearing in nano.

**Comment by ashish-yadav11** [comment]
Also a small bug was introduced from the fix. Try after the latest commit.

**Comment by ashish-yadav11** [comment]
If this also doesn't work, report
1) what replacing
```
		if (term.line[y][x].state != GLYPH_EMPTY) {
```
with
```
		if (term.line[y][x].u != ' ') {
```
does.

2) what replacing
```
		if (term.line[y][x].state != GLYPH_EMPTY) {
```
with
```
		if (1) {
```
does.

**Comment by humky** [comment]
> Try this. After the first while loop in twritetab, add `fprintf(stderr, "writing tab\n");`. After compilation launch by ./st, see if "writing tab" gets printed when letters start disappearing in nano.

It writes "writing tab" at a moment when letter disappear.

1 and 2 are not doing anything new, same exact behavior as before (writing tab message when letter disappear).

**Comment by ashish-yadav11** [comment]
Does the latest commit fix the issue?

**Comment by humky** [comment]
yes, it fixed.

**Comment by ashish-yadav11** [comment]
Ohh yes, finally!

**Comment by humky** [comment]
I just installed bare-bone debian in a VM, and I don't have this bug in there (for previous commit).

**Comment by ashish-yadav11** [comment]
That reproducibility part is beyond me. But the "bug" was in my build.
