### ISSUE TITLE
could the columns relow patch be added to the suckless.org wiki?

### ISSUE THREAD

**Issue by sewnie** [ashish-yadav11/st#4]
https://github.com/BeyondMagic/flarity/blob/master/.patches/columns-rows-reflow-st-unpatched-new.patch

maybe a stripped version of this that only applies on top of the original scrollback patch.

i was originally going to ask @BeyondMagic for it but it seems you are the original author of this patch.

**Comment by ashish-yadav11** [comment]
I will do it once I get some time. This could take long. Meanwhile you can track the progress on the earlier issue opened in this repo only.

**Comment by sewnie** [comment]
mfw i have memory loss and forgot i commented in the 2nd issue

**Comment by ashish-yadav11** [comment]
Its okay.
